before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: KLa1B7UgJ1IZjJ8A6PxlyZNC+/b0ENgN8PQePEvMmnVhJSrZPumud94pf5YKtE/KYEI57NLsuXl5WIXs6fSMb0gIeBLStNNBhxCjF2EZXopiTNQGAzf8npeQMY5/qdUOi8UNHwYahaJFQ/goHzfCgtlAQo+S39q8ISr+lFilAmRPrRNWRtvgcTBicMcSNJMg/bYiGorps6yA87mFdY+FP5ZqLa95rE2o1hdu9gF+IIndfBlreohGe4p1O8OvhQdY7wKje1ZUoKAwHUfoEAuzDb+wm0YG/gF/BiXnMpCvZAyJyZmZkV0/bBbvdVfHVUUAH9WnIyYiCLsGX+CZYveJKcYIyIVShRPDn8lBsOXEzuPN5GNY1AbxPWENQz0ersnUxZnCf/ELVwzGuxRUoSw+uI6d9WnMKrVqKD0kbmI1z2eF2tKOkzLoRK5Y567bA3dRR47nZlWHYtuEdAXavGQpeC7BSTm3VQrwrYEZ/cY0pvobF+0sbPNDarJnWbyX2ZLZ02F6ikwPQuyZlU8FFp3/M2QnsWon2gdf6r7werSmNWZi2nMzdoZ1fXeU8bkN3vKKeg2miIT8xCgJ67IPlMlQmQCx8PUsRLwcdUXdH6yy6Qd5xXMbTTVM7Zl/Sol741LtNdHgvBBLKn9q407FSFjXUP93rNkOsqp7fBSKAHla7DU= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
